<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter sorter">
    <!-- <label class="sorter-label" for="sorter">< ?= $block->escapeHtml(__('Sort By')) ?></label> -->
    <div class="sorter-option">
        <select id="sorter" data-role="sorter" class="sorter-options">
        <option class="sorter-label" selected="selected" style="display: none;"><?= $block->escapeHtml(__('Sort By')) ?></option>
            <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
                <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                    >
                    <?= $block->escapeHtml(__($_order)) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
<script type="text/javascript">
    require(['jquery'], function($){
        $(document).ready( function() {
            $("#sorter").focus(function() {
                $('.sorter').addClass("active");
            });
            $("#sorter").focusout(function() {
                $('.sorter').removeClass("active");
            });
        });
    });
</script>
