<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter sorter" data-mage-init='{
    "collapsible":{
        "animate":{ "duration" :1000, "easing":"easeOutCubic"}
    }}'>
    <label class="sorter-label" for="sorter" data-role="title"><?= $block->escapeHtml(__('Sort By')) ?></label>
    <div data-role="content" class="sorter-option">
        <select id="sorter" data-role="sorter" class="sorter-options">
            <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
                <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                    <?php if ($block->isOrderCurrent($_key)) :?>
                        selected="selected"
                    <?php endif; ?>
                    >
                    <?= $block->escapeHtml(__($_order)) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
