<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>
<?php if ($block->canShowBlock()) : ?>
    <div class="block filter" id="layered-filter-block">
    <div class="filter-custom">
        <span class="filter-button" style="cursor: pointer;">Filter</span>
    </div>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-content filter-content" id="filter-content">
            <div class="filter-clear-custom">
                <?= $block->getChildHtml('state') ?>

                <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                    <div class="block-actions filter-actions">
                        <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear">
                            <span><?= $block->escapeHtml(__('Clear All')) ?></span>
                        </a>
                    </div>
                <?php endif; ?>
            </div>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php if ($filter->getItemsCount()) : ?>
                    <?php if (!$wrapOptions) : ?>
                        <div class="filter-options" id="narrow-by-list" >
                        <?php $wrapOptions = true;
                        endif; ?>
                    <div class="filter-options-item">
                        <div class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?></div>
                        <div class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions) : ?>
                </div>
            <?php else : ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
<script type="text/javascript">
    require(['jquery'], function($){
        $(document).ready( function() {
            var timesClicked = 0;
            $(".filter-button").click(function() {
                timesClicked++;
                if (timesClicked%2==0) {
                    $('.submenu').removeClass("active");
                    $(".breadcrumbs").removeClass("active");
                    $(".page-title").css("display", "block");
                    $(".page-title-wrapper").css("display", "block");
                    $("#layered-filter-block").removeClass("active");
                    $(".filter-button").removeClass("active");
                    $(".toolbar-products").css("paddingTop", "0");
                    $("#modes").css("top", "279px");
                } else {
                    $('.submenu').addClass("active");
                    $(".breadcrumbs").addClass("active");
                    $(".page-title").css("display", "none");
                    $(".page-title-wrapper").css("display", "none");
                    $("#layered-filter-block").addClass("active");
                    $(".filter-button").addClass("active");
                    $(".toolbar-products").css("paddingTop", "8px");
                    $("#modes").css("top", "495px");
                }
            });
        });
    });
</script>