<div class="message">
    <h5 class="message__title">Free shipping</h5>
    <h5 class="message__content">Free shipping on orders over $90</h5>
</div>

// Tiles
<div class="tiles-item">
<img src="{{media url=&quot;wysiwyg/tiles_man.jpg&quot;}}" alt="" />
<a class="hollow-button tiles-button" href="#">Men's Jackets</a>
</div>
<div class="tiles-item">
<img src="{{media url=&quot;wysiwyg/tiles_girl.jpg&quot;}}" alt="" />
<a class="hollow-button tiles-button" href="#">Women's Overalls</a>
</div>

// Journal
<div class="journal__row1">
    <a class="journal-item item-1" href="#">
    <img src="{{media url=&quot;wysiwyg/journal1.jpg&quot;}}" alt="" />
    <p class="journal-item--title">One of One</p>
    <span class="journal-item--status">News</span>
    </a>
    <a class="journal-item item-2" href="#">
    <img src="{{media url=&quot;wysiwyg/journal2.jpg&quot;}}" alt="" />
    <p class="journal-item--title">Cargo Pants For Fall 2019</p>
    <span class="journal-item--status">News</span>
    </a>
    <a class="journal-item item-3" href="#">
    <img src="{{media url=&quot;wysiwyg/journal3.jpg&quot;}}" alt="" />
    <p class="journal-item--title">Leisure Pants For Fall 2019</p>
    <span class="journal-item--status">News</span>
    </a>
</div>
<div class="journal__row2">
    <a class="journal-item item-4" href="#">
    <div class="journal-item--image">
    <img src="{{media url=&quot;wysiwyg/journal4.jpg&quot;}}" alt="" />
    <img src="{{media url=&quot;wysiwyg/journal4.jpg&quot;}}" alt="" />
    </div>
    <p class="journal-item--title">OrtaMiklos</p>
    <span class="journal-item--status">News</span>
    </a>
    <a class="journal-item item-5" href="#">
    <img src="{{media url=&quot;wysiwyg/journal5.jpg&quot;}}" alt="" />
    <p class="journal-item--title">Fall 19 Women’s</p>
    <span class="journal-item--status">News</span>
    </a>
</div>
<div class="journal__button">
    <a class="hollow-button journal-button" href="#">View the journal</a>
</div>

// Footer Social
<ul class="footer-social-inner">
<li><a class="icon-instagram" href="#"></a></li>
<li><a class="icon-facebook" href="#"></a></li>
<li><a class="icon-twitter" href="#"></a></li>
<li><a class="icon-youtube" href="#"></a></li>
<li><a class="icon-soundcloud" href="#"></a></li>
<li><a class="icon-pinterest" href="#"></a></li>
</ul>

// Footer Nav
<div class="footer-nav-inner">
<a class="nav-item" href="#"><h5>FAQ</h5></a>
<a class="nav-item" href="#"><h5>Terms & Conditions</h5></a>
<a class="nav-item" href="#"><h5>IMPRINT</h5></a>
<a class="nav-item" href="#"><h5>PRIVACY STATEMENT</h5></a>
<a class="nav-item" href="#"><h5>JOBS</h5></a>
<a class="nav-item" href="#"><h5>CONTACT</h5></a>
<a class="nav-item" href="#"><h5>HISTORY</h5></a>
<a class="nav-item" href="#"><h5>CORPORATE RESPONSIBILITY</h5></a>
<a class="nav-item" href="#"><h5>Compliance</h5></a>
</div>

// Page
<div class="banner-slider-desktop">
{{widget type="Mageplaza\BannerSlider\Block\Widget" slider_id="1"}}
</div>
<div class="banner-slider-mobile">
{{widget type="Mageplaza\BannerSlider\Block\Widget" slider_id="2"}}
</div>
<div class="message">
{{widget type="Magento\Cms\Block\Widget\Block" template="widget/static_block/default.phtml" block_id="19"}}
</div>
<div class="tiles">
{{widget type="Magento\Cms\Block\Widget\Block" template="widget/static_block/default.phtml" block_id="20"}}
</div>
<div class="journal">
{{widget type="Magento\Cms\Block\Widget\Block" template="widget/static_block/default.phtml" block_id="21"}}
</div>
<div class="tiles2">
{{widget type="Magento\Cms\Block\Widget\Block" template="widget/static_block/default.phtml" block_id="22"}}
</div>

// Banner
<img src="{{media url=&quot;wysiwyg/hero_banner1.jpg&quot;}}" alt="" />
<div class="banner-content">
<div class="banner-text">   
<h1>Everyday Carry</h1>
<p>Based on time-honored classics, this early-season selection of shirts and pants nod to Carhartt WIP’s working roots.</p>
</div>
<div class="banner-button">
<a class="hollow-button item" href="#">Shop Now</a>
<a class="hollow-button item" href="#">Learn More</a>
</div>
</div>