<h2>Buttons</h2>
<p><button class="hollow-button" type="submit">Hollow</button></p>
<h2>Input Fields</h2>
<div class="control"><select id="select" name="select">
<option value="">Please select</option>
<option value="1">Option One</option>
<option value="2">Option Two</option>
<option value="3">Option Three</option>
<option value="4">Option Four</option>
</select></div>
<div><input class="mage-error" type="text" placeholder="email@li.com">
<div class="mage-error">Please enter a valid email address</div>
</div>
<div><input class="input-text" type="text" placeholder="Text field"></div>
</div>
<div>

<h2>Journal & Tiles</h2>
<div>
    <a class="journal-item">
        <img src="<?= $this->getViewFileUrl('images/style-guide.png'); ?>" alt="">
        <p class="journal-item--title">One of One</p>
        <span class="journal-item--status">News</span>
    </a>
</div>
<div>
    <div class="tiles-item">
        <img src="<?= $this->getViewFileUrl('images/style-guide1.png'); ?>" alt="">
        <a class="hollow-button tiles-button" href="#">Women's Overall</a>
    </div>
</div>
<h2>Icon</h2>
<ul class="footer-social-inner">
<li><a class="icon-instagram" href="#"></a></li>
<li><a class="icon-facebook" href="#"></a></li>
<li><a class="icon-twitter" href="#"></a></li>
<li><a class="icon-youtube" href="#"></a></li>
<li><a class="icon-soundcloud" href="#"></a></li>
<li><a class="icon-pinterest" href="#"></a></li>
</ul>