<?php
	$quantity =  $block->getBestSellerData();
	$imageId = 'category_page_grid';
	?>
	<h1>Best Seller Collection.....</h1>
	<ul>
	<?php foreach ($quantity as $product) {
		?>
		<li><?php  echo $product->getProductName();?>
		<?php  
		echo $product->getProductUrl();
		echo number_format($product->getQtyOrdered());?></li>
        <div class="price-box">
		<?php $price = $block->getPriceById($product->getProductId());
			echo $block->getCurrencyWithFormat($price);
		?></div>
	<?php } ?>
</ul>